const icons={home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5z"/><path d="M9 21v-7h6v7"/></svg>',calendar:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/></svg>',trends:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/></svg>',knowledge:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 4.5v17M8 6h8"/></svg>',profile:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>'};
const nav=[['home','棣栭〉'],['calendar','鏃ュ巻'],['trends','瓒嬪娍'],['knowledge','鐭ヨ瘑'],['profile','鎴戠殑']];
const today=new Date();
const iso=d=>{const x=new Date(d); x.setMinutes(x.getMinutes()-x.getTimezoneOffset()); return x.toISOString().slice(0,10)};
const fmt=(d,opt={month:'long',day:'numeric'})=>new Intl.DateTimeFormat('zh-CN',opt).format(new Date(d));
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const defaultState={page:'home',onboarded:false,lastStart:iso(add(today,-10)),periodLength:5,cycleLength:28,periodActive:false,logs:{},sync:false,reminders:false,quiet:true};
let state={...defaultState,...JSON.parse(localStorage.getItem('cyclea-state')||'{}')};
const save=()=>localStorage.setItem('cyclea-state',JSON.stringify(state));
const predictedStart=add(new Date(state.lastStart),state.cycleLength);
const predStart=()=>add(predictedStart,-2), predEnd=()=>add(predictedStart,2);
function renderNav(){document.querySelectorAll('.side-nav,.mobile-nav').forEach(el=>el.innerHTML=nav.map(([id,label])=>`<button class="nav-btn ${state.page===id?'active':''}" data-action="navigate" data-page="${id}" aria-label="${label}">${icons[id]}<span>${label}</span></button>`).join(''))}
function pageHeader(kicker,title,desc,action='<button class="icon-btn" aria-label="闅愮鐘舵€?>鈱?/button>'){return `<header class="page-header"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div><div class="header-actions">${action}</div></header>`}
function currentDay(){return Math.max(1,Math.floor((today-new Date(state.lastStart))/86400000)+1)}
function weekStrip(){const monday=add(today,-((today.getDay()+6)%7));return `<div class="week-strip">${[0,1,2,3,4,5,6].map(i=>{const d=add(monday,i),key=iso(d),period=(d>=new Date(state.lastStart)&&d<=add(new Date(state.lastStart),state.periodLength-1));return `<div class="day ${iso(d)===iso(today)?'today':''} ${period?'period':''}"><span>${'涓€浜屼笁鍥涗簲鍏棩'[i]}</span><strong>${d.getDate()}</strong>${state.logs[key]||period?'<i class="mini-dot"></i>':''}</div>`}).join('')}</div>`}
function home(){const day=currentDay();return `${pageHeader('浠婂ぉ 路 '+fmt(today,{month:'long',day:'numeric',weekday:'long'}),'鏃╀笂濂斤紝鏋楃劧','鑺变竴鍒嗛挓锛屽拰鑷繁鐨勮韩浣撴墦涓嫑鍛笺€?,'<button class="ghost-btn" data-action="privacy">闅愮妯″紡</button><button class="primary-btn" data-action="quickLog">锛?浠婃棩鎵撳崱</button>')}
<div class="grid dashboard-grid"><div class="grid">
<section class="card cycle-card"><div class="card-title"><span class="eyebrow">褰撳墠鍛ㄦ湡</span><span class="subtle">鍒氬垰鏇存柊</span></div><div class="cycle-status"><div class="cycle-ring"><div class="cycle-ring-content"><strong>${state.periodActive?'绗?'+day:'绗?'+day}</strong><span>${state.periodActive?'缁忔湡澶╂暟':'鍛ㄦ湡澶╂暟'}</span></div></div><div class="cycle-copy"><h2>${state.periodActive?'缁忔湡绗?'+day+' 澶?:'澶勪簬鍛ㄦ湡涓'}</h2><p>${state.periodActive?'璁板緱鐓ч【濂借嚜宸憋紝璁板綍娴侀噺鑳借瓒嬪娍鏇存竻鏅般€?:`涓嬫缁忔湡棰勮鍦?${fmt(predStart())}鈥?{fmt(predEnd())} 寮€濮嬨€俙}<br>杩欐槸鍩轰簬浣犺繎鏈熻褰曠殑缁熻浼拌銆?/p><span class="prediction-pill"><i class="dot"></i> 缃俊搴?路 涓瓑銆€鈱?/span></div></div></section>
<section class="card quick-card"><div class="card-title"><h2>蹇嵎璁板綍</h2><button class="text-link" data-action="quickLog">灞曞紑鍏ㄩ儴</button></div><div class="quick-actions"><button class="quick-action" data-action="period"><span class="action-icon">鈼?/span>${state.periodActive?'缁撴潫缁忔湡':'寮€濮嬬粡鏈?}</button><button class="quick-action" data-action="log" data-type="flow"><span class="action-icon">鈾?/span>娴侀噺</button><button class="quick-action" data-action="log" data-type="pain"><span class="action-icon">鈱?/span>鐤肩棝</button><button class="quick-action" data-action="log" data-type="mood"><span class="action-icon">鈽?/span>鎯呯华</button></div></section>
<section class="card"><div class="card-title"><h2>杩囧幓 7 澶?/h2><button class="text-link" data-action="navigate" data-page="calendar">鏌ョ湅鏃ュ巻 鈫?/button></div>${weekStrip()}</section></div>
<div class="grid" style="align-content:start"><section class="card"><div class="insight"><span class="insight-icon">鉁?/span><div><div class="eyebrow">浠婃棩娲炲療</div><h3>涓鸿韩浣撶暀涓€鐐逛綑閲?/h3><p>缁忔湡鍓嶅悗绮惧姏娉㈠姩寰堝父瑙併€傝嫢浠婂ぉ鎰熻鐤叉儷锛屽彲浠ラ檷浣庤繍鍔ㄥ己搴︼紝骞朵繚璇佸厖瓒崇潯鐪犮€?/p><button class="text-link" data-action="navigate" data-page="knowledge" style="margin-top:12px">浜嗚В鏇村 鈫?/button></div></div></section>
<section class="card"><div class="card-title"><h3>鏈懆鏈熸瑙?/h3><span class="subtle">${state.cycleLength} 澶╁懆鏈?/span></div><div class="record-list"><div class="record-item"><span>鈼?/span><div><strong>棰勬祴鍖洪棿</strong><small>${fmt(predStart())}鈥?{fmt(predEnd())}</small></div></div><div class="record-item"><span>鈱?/span><div><strong>鏈湴淇濆瓨</strong><small>${Object.keys(state.logs).length} 鏉℃瘡鏃ヨ褰?/small></div></div></div></section></div></div>`}
function calendar(){const view=new Date(today.getFullYear(),today.getMonth(),1),start=new Date(view);start.setDate(1-((view.getDay()+6)%7));const days=Array.from({length:42},(_,i)=>add(start,i));return `${pageHeader('浣犵殑璁板綍','鍛ㄦ湡鏃ュ巻','宸茶褰曚笌棰勬祴鏃ユ湡浣跨敤涓嶅悓鏍囪锛屼笉鎶婁及璁″綋浣滅‘瀹氭棩鏈熴€?,'<button class="primary-btn" data-action="period">锛?琛ヨ缁忔湡</button>')}<div class="calendar-layout"><section class="card calendar-card"><div class="calendar-head"><button class="icon-btn">鈥?/button><h2>${fmt(view,{year:'numeric',month:'long'})}</h2><button class="icon-btn">鈥?/button></div><div class="calendar-grid">${'涓€浜屼笁鍥涗簲鍏棩'.split('').map(x=>`<div class="weekday">鍛?{x}</div>`).join('')}${days.map(d=>{const key=iso(d),isPeriod=d>=new Date(state.lastStart)&&d<=add(new Date(state.lastStart),state.periodLength-1),pred=d>=predStart()&&d<=predEnd();return `<button class="cal-day ${d.getMonth()!==view.getMonth()?'muted':''} ${isPeriod?'period':''} ${pred?'predicted':''} ${key===iso(today)?'today':''} ${state.logs[key]?'has-log':''}" data-action="date" data-date="${key}">${d.getDate()}</button>`}).join('')}</div><div class="legend"><span><i class="recorded"></i>宸茶褰曠粡鏈?/span><span><i class="pred"></i>棰勬祴鍖洪棿</span><span><i class="symptom"></i>鏈夌棁鐘惰褰?/span></div></section><aside class="side-stack"><section class="card date-panel"><span class="eyebrow">浠婂ぉ</span><div class="big-date">${today.getDate()} 鏃?/div><p class="subtle">鍛ㄦ湡绗?${currentDay()} 澶?/p><div class="record-list"><div class="record-item"><span>鈽?/span><div><strong>杩樻病鏈変粖鏃ヨ褰?/strong><small>鎵撳崱閫氬父鍙渶 10 绉?/small></div></div></div><button class="secondary-btn" data-action="quickLog" style="width:100%;margin-top:18px">璁板綍浠婂ぉ</button></section><section class="card"><h3>棰勬祴璇存槑</h3><p class="subtle" style="line-height:1.7">鐩墠鏈?3 涓湁鏁堝懆鏈燂紝杩戞湡瀛樺湪杞诲井娉㈠姩锛屽洜姝ゅ睍绀?5 澶╅娴嬬獥鍙ｃ€?/p><span class="prediction-pill"><i class="dot"></i>涓瓑缃俊搴?/span></section></aside></div>`}
function trends(){const vals=[27,29,28,31,28,29];return `${pageHeader('浜嗚В鍙樺寲','瓒嬪娍涓庢礊瀵?,'瓒嬪娍甯姪浣犵湅瑙佸彉鍖栵紝涓嶇敤浜庤瘖鏂柧鐥呫€?,'<button class="ghost-btn" data-action="export">瀵煎嚭鎶ュ憡</button>')}<div class="grid metrics"><section class="card metric"><span class="subtle">骞冲潎鍛ㄦ湡</span><strong>28.7<small> 澶?/small></strong><span class="trend-up">鍦ㄤ綘鐨勫父瑙佽寖鍥村唴</span></section><section class="card metric"><span class="subtle">骞冲潎缁忔湡</span><strong>5.2<small> 澶?/small></strong><span class="trend-up">杈冪ǔ瀹?/span></section><section class="card metric"><span class="subtle">璁板綍瀹屾暣搴?/span><strong>82<small>%</small></strong><span class="trend-up">姣斾笂鍛ㄦ湡澶?2 澶?/span></section></div><div class="grid dashboard-grid" style="margin-top:22px"><section class="card chart-card"><div class="card-title"><h2>鏈€杩?6 涓懆鏈?/h2><span class="subtle">鍛ㄦ湡闀垮害锛堝ぉ锛?/span></div><div class="bar-chart">${vals.map((v,i)=>`<div class="bar-wrap"><div class="bar ${i===vals.length-1?'active':''}" style="height:${v/35*100}%" title="${v} 澶?></div><span class="bar-label">${i+1}鏈?/span></div>`).join('')}</div><p class="line-legend">浣犵殑鍛ㄦ湡澶у鍦?27鈥?1 澶╀箣闂达紝杩戞湡娉㈠姩杈冨皬銆?/p></section><section class="card"><div class="card-title"><h2>甯歌鐥囩姸</h2><span class="subtle">杩?3 涓懆鏈?/span></div>${[['杞诲井鑵圭棝',76],['鐤叉儷',58],['鎯呯华娉㈠姩',42],['鐫＄湢涓嶄匠',28]].map(([n,v])=>`<div class="symptom-row"><header><span>${n}</span><span>${v}%</span></header><div class="progress"><i style="width:${v}%"></i></div></div>`).join('')}<p class="subtle" style="line-height:1.6">鏍锋湰閲忎粛杈冨皯锛屾垜浠笉浼氭嵁姝ゅ垽鏂洜鏋滃叧绯汇€?/p></section></div>`}
function knowledge(){const data=[['鈽?,'鍛ㄦ湡鍩虹','涓轰粈涔堥娴嬫槸涓€涓棩鏈熻寖鍥达紵','鍛ㄦ湡浼氳嚜鐒舵尝鍔ㄣ€傚尯闂存瘮鍗曚竴鏃ユ湡鏇磋兘璇氬疄琛ㄨ揪涓嶇‘瀹氭€с€?],['鈮?,'娓╁拰鑷姢','缁忔湡鍓嶅悗锛屾€庢牱瀹夋帓杩愬姩锛?,'鍙互鏍规嵁褰撳ぉ鎰熷彈璋冩暣寮哄害锛屾俯鍜屾椿鍔ㄤ篃鏈変环鍊笺€?],['鉁?,'寤鸿鍏虫敞','浠€涔堟椂鍊欒鍜ㄨ涓撲笟鍖荤敓锛?,'鐤肩棝鎸佺画褰卞搷鐢熸椿鎴栧嚭琛€閲忔槑鏄炬敼鍙樻椂锛屽缓璁強鏃跺挩璇€?],['鈼?,'韬綋鐞嗚В','鍘嬪姏涓庡懆鏈熷彉鍖栨湁鍏冲悧锛?,'鍘嬪姏鍙兘涓庡懆鏈熷彉鍖栧悓鏃跺嚭鐜帮紝浣嗗崟娆″彉鍖栨棤娉曡鏄庡洜鏋溿€?],['鈱?,'璁板綍鎶€宸?,'鎬庢牱鐢?10 绉掑畬鎴愭瘡鏃ヨ褰曪紵','鍙褰曚粖澶╂渶鏄庢樉鐨勪竴椤规劅鍙楋紝鎸佺画姣斿畬鏁存洿閲嶈銆?],['鈾?,'闅愮涓庡畨鍏?,'浣犵殑鍋ュ悍璁板綍淇濆瓨鍦ㄥ摢閲岋紵','娓稿妯″紡鐨勬暟鎹粎淇濆瓨鍦ㄥ綋鍓嶆祻瑙堝櫒锛屽彲闅忔椂瀵煎嚭鎴栧垹闄ゃ€?]];return `${pageHeader('鍏嬪埗銆佸彲淇?,'鐭ヨ瘑灏忕珯','鍙彁渚涗笌浣犲綋鍓嶉樁娈电浉鍏崇殑鐭唴瀹癸紝骞舵竻妤氭爣娉ㄨ竟鐣屻€?,'<button class="ghost-btn">鈱?鎼滅储</button>')}<div class="grid articles">${data.map(x=>`<article class="card article-card"><div class="article-cover">${x[0]}</div><div class="article-body"><span class="tag">${x[1]}</span><h3>${x[2]}</h3><p>${x[3]}</p><span class="source">鍖诲椤鹃棶瀹℃牳 路 鏇存柊浜?2026.06</span></div></article>`).join('')}</div>`}
function profile(){return `${pageHeader('璐︽埛涓庢暟鎹?,'鎴戠殑','鎵€鏈夋晱鎰熻兘鍔涢兘鐢变綘涓诲姩寮€鍚€?,'<button class="primary-btn" data-action="export">瀵煎嚭鏁版嵁</button>')}<div class="grid settings-grid"><section class="card setting-card"><div class="card-title"><h2>闅愮涓庢暟鎹?/h2><span class="data-badge">鏈湴浼樺厛</span></div><div class="setting-row"><div><strong>浜戠鍚屾</strong><small>寮€鍚墠浼氬崟鐙鏄庢暟鎹敤閫?/small></div><button class="toggle ${state.sync?'on':''}" data-action="toggle" data-key="sync" aria-label="浜戠鍚屾"></button></div><div class="setting-row"><div><strong>鏁版嵁鍦板浘</strong><small>鏌ョ湅鏀堕泦瀛楁銆佺敤閫斾笌淇濆瓨浣嶇疆</small></div><button class="text-link" data-action="privacy">鏌ョ湅 鈫?/button></div><div class="setting-row"><div><strong>瀵煎嚭璁板綍</strong><small>CSV / JSON锛屾湰鍦扮敓鎴?/small></div><button class="text-link" data-action="export">瀵煎嚭 鈫?/button></div><div class="setting-row"><div><strong>鍒犻櫎鎵€鏈夋暟鎹?/strong><small>鍒犻櫎鍚庢棤娉曟仮澶?/small></div><button class="ghost-btn danger-btn" data-action="delete">鍒犻櫎</button></div></section><section class="card setting-card"><div class="card-title"><h2>鎻愰啋璁剧疆</h2><span class="subtle">榛樿鍏抽棴</span></div><div class="setting-row"><div><strong>缁忔湡灏嗚嚦鎻愰啋</strong><small>浣跨敤涓€ф枃妗堬紝涓嶅湪閿佸睆鏄剧ず鏁忔劅鍐呭</small></div><button class="toggle ${state.reminders?'on':''}" data-action="toggle" data-key="reminders" aria-label="缁忔湡鎻愰啋"></button></div><div class="setting-row"><div><strong>闈欓粯鏃舵</strong><small>22:00鈥?8:00</small></div><button class="toggle ${state.quiet?'on':''}" data-action="toggle" data-key="quiet" aria-label="闈欓粯鏃舵"></button></div><div class="setting-row"><div><strong>璁板綍鎻愰啋</strong><small>缁忔湡涓瘡澶╂渶澶氫竴娆?/small></div><span class="subtle">鏈紑鍚?/span></div></section><section class="card setting-card"><div class="card-title"><h2>鍛ㄦ湡鍋忓ソ</h2></div><div class="setting-row"><div><strong>浣跨敤妯″紡</strong><small>缁忔湡绠＄悊</small></div><button class="text-link">淇敼 鈫?/button></div><div class="setting-row"><div><strong>閫氬父鍛ㄦ湡</strong><small>${state.cycleLength} 澶?/small></div><button class="text-link">淇敼 鈫?/button></div></section><section class="card setting-card"><div class="card-title"><h2>鍏充簬 Cyclea</h2></div><p class="subtle" style="line-height:1.8">Cyclea 鎻愪緵璁板綍鍜岀粺璁′及璁★紝涓嶆瀯鎴愬尰鐤楄瘖鏂€侀伩瀛曟壙璇烘垨鍙楀瓡淇濊瘉銆傚嚭鐜扮揣鎬ョ棁鐘舵椂锛岃浼樺厛鑱旂郴褰撳湴绱ф€ュ尰鐤楁湇鍔°€?/p></section></div>`}
function render(){renderNav();document.getElementById('main').innerHTML=({home,calendar,trends,knowledge,profile}[state.page]||home)();document.getElementById('main').focus({preventScroll:true});save()}
function showModal(html){const m=document.getElementById('modal');m.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true">${html}</div>`;m.hidden=false}
function closeModal(){document.getElementById('modal').hidden=true}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function onboarding(){showModal(`<div class="onboard-mark">C</div><span class="eyebrow" style="display:block;margin-top:18px">娆㈣繋鏉ュ埌 Cyclea</span><h2>鏇翠簡瑙ｅ懆鏈燂紝涔熸洿瀹夊績銆?/h2><p>涓嶆敞鍐屼篃鍙互浣跨敤銆傚彧闇€瑕佹渶杩戜竴娆＄粡鏈熶俊鎭紝灏辫兘寰楀埌绗竴涓娴嬪尯闂淬€?/p><div class="form-group"><label>鏈€杩戜竴娆＄粡鏈熷紑濮嬫棩</label><input id="onboardDate" type="date" value="${state.lastStart}" max="${iso(today)}"></div><div class="form-group"><label>閫氬父鍛ㄦ湡闀垮害锛堝ぉ锛?/label><input id="onboardCycle" type="number" min="20" max="60" value="${state.cycleLength}"></div><div class="privacy-promise">鈱?鏁版嵁榛樿鍙繚瀛樺湪杩欏彴璁惧锛岄殢鏃跺彲浠ュ鍑烘垨鍒犻櫎銆?/div><div class="modal-actions"><button class="ghost-btn" data-action="onboardSkip">绋嶅悗璁剧疆</button><button class="primary-btn" data-action="onboardDone">浠ユ父瀹㈣韩浠藉紑濮?/button></div>`) }
function logModal(type){const labels={flow:['璁板綍娴侀噺',['鐐规淮','灏?,'涓?,'澶?]],pain:['璁板綍鐤肩棝',['鏃?,'杞?,'涓?,'閲?]],mood:['璁板綍鎯呯华',['骞抽潤','鏁忔劅','浣庤惤','鎰夊揩']]},x=labels[type]||['浠婃棩鎵撳崱',['娴侀噺','鐤肩棝','鎯呯华','鐫＄湢']];showModal(`<span class="eyebrow">${fmt(today,{month:'long',day:'numeric'})}</span><h2>${x[0]}</h2><p>閫夋嫨鏈€鎺ヨ繎浠婂ぉ鎰熷彈鐨勪竴椤癸紝涔熷彲浠ョ暀绌恒€?/p><div class="choice-grid">${x[1].map((n,i)=>`<button class="choice ${i===1?'selected':''}" data-choice="${n}">${n}</button>`).join('')}</div><div class="form-group"><label>绉佸瘑澶囨敞锛堜笉浼氶粯璁よ繘鍏ユ姤鍛婏級</label><textarea id="note" placeholder="鍐欎笅涓€鐐规兂璁颁綇鐨勪簨鈥?></textarea></div><div class="modal-actions"><button class="ghost-btn" data-action="close">鍙栨秷</button><button class="primary-btn" data-action="saveLog" data-type="${type}">淇濆瓨璁板綍</button></div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='navigate'){state.page=b.dataset.page;render()}if(a==='close')closeModal();if(a==='quickLog')logModal('all');if(a==='log')logModal(b.dataset.type);if(a==='saveLog'){const selected=document.querySelector('.choice.selected')?.dataset.choice||'宸茶褰?;state.logs[iso(today)]={...(state.logs[iso(today)]||{}),[b.dataset.type]:selected,note:document.getElementById('note')?.value||''};closeModal();render();toast('宸插畨鍏ㄤ繚瀛樺湪姝よ澶?)}if(a==='period'){state.periodActive=!state.periodActive;if(state.periodActive)state.lastStart=iso(today);render();toast(state.periodActive?'宸茶褰曚粖澶╁紑濮?:'缁忔湡宸茬粨鏉熷苟淇濆瓨')}if(a==='toggle'){state[b.dataset.key]=!state[b.dataset.key];render();toast(state[b.dataset.key]?'宸插紑鍚?:'宸插叧闂?)}if(a==='onboardDone'){state.lastStart=document.getElementById('onboardDate').value;state.cycleLength=Number(document.getElementById('onboardCycle').value)||28;state.onboarded=true;closeModal();render();toast('浣犵殑绗竴涓娴嬪尯闂村凡鐢熸垚')}if(a==='onboardSkip'){state.onboarded=true;closeModal();render()}if(a==='privacy')showModal(`<span class="eyebrow">闅愮鐘舵€?/span><h2>浣犵殑鏁版嵁锛岀敱浣犳帉鎺?/h2><div class="record-list"><div class="record-item"><span>鈱?/span><div><strong>鍛ㄦ湡涓庣棁鐘惰褰?/strong><small>浠呬繚瀛樺湪褰撳墠娴忚鍣?/small></div></div><div class="record-item"><span>鈼?/span><div><strong>浜戝悓姝?/strong><small>${state.sync?'宸插紑鍚?:'鏈紑鍚?}</small></div></div><div class="record-item"><span>脳</span><div><strong>骞垮憡涓庤法绔欒拷韪?/strong><small>涓嶄娇鐢?/small></div></div></div><div class="modal-actions"><button class="primary-btn" data-action="close">鐭ラ亾浜?/button></div>`);if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='cyclea-data.json';link.click();URL.revokeObjectURL(url);toast('鏁版嵁宸插湪鏈湴鐢熸垚')}if(a==='delete')showModal(`<span class="eyebrow">涓嶅彲鎾ら攢</span><h2>鍒犻櫎鎵€鏈夋湰鍦版暟鎹紵</h2><p>鍒犻櫎鍚庡皢鏃犳硶鎭㈠杩欎簺璁板綍銆傛鎿嶄綔鍙奖鍝嶅綋鍓嶈澶囥€?/p><div class="modal-actions"><button class="ghost-btn" data-action="close">鍙栨秷</button><button class="ghost-btn danger-btn" data-action="confirmDelete">纭鍒犻櫎</button></div>`);if(a==='confirmDelete'){localStorage.removeItem('cyclea-state');state={...defaultState,onboarded:true};closeModal();render();toast('鏈湴鏁版嵁宸插垹闄?)}if(a==='date')logModal('all')});
document.addEventListener('click',e=>{const c=e.target.closest('.choice');if(c){c.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}});
render();if(!state.onboarded)setTimeout(onboarding,250);

