const icons={home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5z"/><path d="M9 21v-7h6v7"/></svg>',calendar:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/></svg>',trends:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/></svg>',knowledge:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 4.5v17M8 6h8"/></svg>',profile:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>'};
const nav=[['home','首页'],['calendar','日历'],['trends','趋势'],['knowledge','知识'],['profile','我的']];
const today=new Date();
const iso=d=>{const x=new Date(d); x.setMinutes(x.getMinutes()-x.getTimezoneOffset()); return x.toISOString().slice(0,10)};
const fmt=(d,opt={month:'long',day:'numeric'})=>new Intl.DateTimeFormat('zh-CN',opt).format(new Date(d));
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const defaultState={page:'home',onboarded:false,lastStart:iso(add(today,-10)),periodLength:5,cycleLength:28,periodActive:false,logs:{},sync:false,reminders:false,quiet:true};
let state={...defaultState,...JSON.parse(localStorage.getItem('cyclea-state')||'{}')};
const save=()=>localStorage.setItem('cyclea-state',JSON.stringify(state));
const predictedStart=add(new Date(state.lastStart),state.cycleLength);
const predStart=()=>add(predictedStart,-2), predEnd=()=>add(predictedStart,2);
function renderNav(){document.querySelectorAll('.side-nav,.mobile-nav').forEach(el=>el.innerHTML=nav.map(([id,label])=>`<button class="nav-btn ${state.page===id?'active':''}" data-action="navigate" data-page="${id}" aria-label="${label}">${icons[id]}<span>${label}</span></button>`).join(''))}
function pageHeader(kicker,title,desc,action='<button class="icon-btn" aria-label="隐私状态">⌁</button>'){return `<header class="page-header"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div><div class="header-actions">${action}</div></header>`}
function currentDay(){return Math.max(1,Math.floor((today-new Date(state.lastStart))/86400000)+1)}
function weekStrip(){const monday=add(today,-((today.getDay()+6)%7));return `<div class="week-strip">${[0,1,2,3,4,5,6].map(i=>{const d=add(monday,i),key=iso(d),period=(d>=new Date(state.lastStart)&&d<=add(new Date(state.lastStart),state.periodLength-1));return `<div class="day ${iso(d)===iso(today)?'today':''} ${period?'period':''}"><span>${'一二三四五六日'[i]}</span><strong>${d.getDate()}</strong>${state.logs[key]||period?'<i class="mini-dot"></i>':''}</div>`}).join('')}</div>`}
function home(){const day=currentDay();return `${pageHeader('今天 · '+fmt(today,{month:'long',day:'numeric',weekday:'long'}),'早上好，林然','花一分钟，和自己的身体打个招呼。','<button class="ghost-btn" data-action="privacy">隐私模式</button><button class="primary-btn" data-action="quickLog">＋ 今日打卡</button>')}
<div class="grid dashboard-grid"><div class="grid">
<section class="card cycle-card"><div class="card-title"><span class="eyebrow">当前周期</span><span class="subtle">刚刚更新</span></div><div class="cycle-status"><div class="cycle-ring"><div class="cycle-ring-content"><strong>${state.periodActive?'第 '+day:'第 '+day}</strong><span>${state.periodActive?'经期天数':'周期天数'}</span></div></div><div class="cycle-copy"><h2>${state.periodActive?'经期第 '+day+' 天':'处于周期中段'}</h2><p>${state.periodActive?'记得照顾好自己，记录流量能让趋势更清晰。':`下次经期预计在 ${fmt(predStart())}—${fmt(predEnd())} 开始。`}<br>这是基于你近期记录的统计估计。</p><span class="prediction-pill"><i class="dot"></i> 置信度 · 中等　⌄</span></div></div></section>
<section class="card quick-card"><div class="card-title"><h2>快捷记录</h2><button class="text-link" data-action="quickLog">展开全部</button></div><div class="quick-actions"><button class="quick-action" data-action="period"><span class="action-icon">◒</span>${state.periodActive?'结束经期':'开始经期'}</button><button class="quick-action" data-action="log" data-type="flow"><span class="action-icon">♒</span>流量</button><button class="quick-action" data-action="log" data-type="pain"><span class="action-icon">⌁</span>疼痛</button><button class="quick-action" data-action="log" data-type="mood"><span class="action-icon">☼</span>情绪</button></div></section>
<section class="card"><div class="card-title"><h2>过去 7 天</h2><button class="text-link" data-action="navigate" data-page="calendar">查看日历 →</button></div>${weekStrip()}</section></div>
<div class="grid" style="align-content:start"><section class="card"><div class="insight"><span class="insight-icon">✦</span><div><div class="eyebrow">今日洞察</div><h3>为身体留一点余量</h3><p>经期前后精力波动很常见。若今天感觉疲惫，可以降低运动强度，并保证充足睡眠。</p><button class="text-link" data-action="navigate" data-page="knowledge" style="margin-top:12px">了解更多 →</button></div></div></section>
<section class="card"><div class="card-title"><h3>本周期概览</h3><span class="subtle">${state.cycleLength} 天周期</span></div><div class="record-list"><div class="record-item"><span>◷</span><div><strong>预测区间</strong><small>${fmt(predStart())}—${fmt(predEnd())}</small></div></div><div class="record-item"><span>⌁</span><div><strong>本地保存</strong><small>${Object.keys(state.logs).length} 条每日记录</small></div></div></div></section></div></div>`}
function calendar(){const view=new Date(today.getFullYear(),today.getMonth(),1),start=new Date(view);start.setDate(1-((view.getDay()+6)%7));const days=Array.from({length:42},(_,i)=>add(start,i));return `${pageHeader('你的记录','周期日历','已记录与预测日期使用不同标记，不把估计当作确定日期。','<button class="primary-btn" data-action="period">＋ 补记经期</button>')}<div class="calendar-layout"><section class="card calendar-card"><div class="calendar-head"><button class="icon-btn">‹</button><h2>${fmt(view,{year:'numeric',month:'long'})}</h2><button class="icon-btn">›</button></div><div class="calendar-grid">${'一二三四五六日'.split('').map(x=>`<div class="weekday">周${x}</div>`).join('')}${days.map(d=>{const key=iso(d),isPeriod=d>=new Date(state.lastStart)&&d<=add(new Date(state.lastStart),state.periodLength-1),pred=d>=predStart()&&d<=predEnd();return `<button class="cal-day ${d.getMonth()!==view.getMonth()?'muted':''} ${isPeriod?'period':''} ${pred?'predicted':''} ${key===iso(today)?'today':''} ${state.logs[key]?'has-log':''}" data-action="date" data-date="${key}">${d.getDate()}</button>`}).join('')}</div><div class="legend"><span><i class="recorded"></i>已记录经期</span><span><i class="pred"></i>预测区间</span><span><i class="symptom"></i>有症状记录</span></div></section><aside class="side-stack"><section class="card date-panel"><span class="eyebrow">今天</span><div class="big-date">${today.getDate()} 日</div><p class="subtle">周期第 ${currentDay()} 天</p><div class="record-list"><div class="record-item"><span>☼</span><div><strong>还没有今日记录</strong><small>打卡通常只需 10 秒</small></div></div></div><button class="secondary-btn" data-action="quickLog" style="width:100%;margin-top:18px">记录今天</button></section><section class="card"><h3>预测说明</h3><p class="subtle" style="line-height:1.7">目前有 3 个有效周期，近期存在轻微波动，因此展示 5 天预测窗口。</p><span class="prediction-pill"><i class="dot"></i>中等置信度</span></section></aside></div>`}
function trends(){const vals=[27,29,28,31,28,29];return `${pageHeader('了解变化','趋势与洞察','趋势帮助你看见变化，不用于诊断疾病。','<button class="ghost-btn" data-action="export">导出报告</button>')}<div class="grid metrics"><section class="card metric"><span class="subtle">平均周期</span><strong>28.7<small> 天</small></strong><span class="trend-up">在你的常见范围内</span></section><section class="card metric"><span class="subtle">平均经期</span><strong>5.2<small> 天</small></strong><span class="trend-up">较稳定</span></section><section class="card metric"><span class="subtle">记录完整度</span><strong>82<small>%</small></strong><span class="trend-up">比上周期多 2 天</span></section></div><div class="grid dashboard-grid" style="margin-top:22px"><section class="card chart-card"><div class="card-title"><h2>最近 6 个周期</h2><span class="subtle">周期长度（天）</span></div><div class="bar-chart">${vals.map((v,i)=>`<div class="bar-wrap"><div class="bar ${i===vals.length-1?'active':''}" style="height:${v/35*100}%" title="${v} 天"></div><span class="bar-label">${i+1}月</span></div>`).join('')}</div><p class="line-legend">你的周期大多在 27—31 天之间，近期波动较小。</p></section><section class="card"><div class="card-title"><h2>常见症状</h2><span class="subtle">近 3 个周期</span></div>${[['轻微腹痛',76],['疲惫',58],['情绪波动',42],['睡眠不佳',28]].map(([n,v])=>`<div class="symptom-row"><header><span>${n}</span><span>${v}%</span></header><div class="progress"><i style="width:${v}%"></i></div></div>`).join('')}<p class="subtle" style="line-height:1.6">样本量仍较少，我们不会据此判断因果关系。</p></section></div>`}
function knowledge(){const data=[['☾','周期基础','为什么预测是一个日期范围？','周期会自然波动。区间比单一日期更能诚实表达不确定性。'],['≈','温和自护','经期前后，怎样安排运动？','可以根据当天感受调整强度，温和活动也有价值。'],['✦','建议关注','什么时候该咨询专业医生？','疼痛持续影响生活或出血量明显改变时，建议及时咨询。'],['◌','身体理解','压力与周期变化有关吗？','压力可能与周期变化同时出现，但单次变化无法说明因果。'],['⌁','记录技巧','怎样用 10 秒完成每日记录？','只记录今天最明显的一项感受，持续比完整更重要。'],['♡','隐私与安全','你的健康记录保存在哪里？','游客模式的数据仅保存在当前浏览器，可随时导出或删除。']];return `${pageHeader('克制、可信','知识小站','只提供与你当前阶段相关的短内容，并清楚标注边界。','<button class="ghost-btn">⌕ 搜索</button>')}<div class="grid articles">${data.map(x=>`<article class="card article-card"><div class="article-cover">${x[0]}</div><div class="article-body"><span class="tag">${x[1]}</span><h3>${x[2]}</h3><p>${x[3]}</p><span class="source">医学顾问审核 · 更新于 2026.06</span></div></article>`).join('')}</div>`}
function profile(){return `${pageHeader('账户与数据','我的','所有敏感能力都由你主动开启。','<button class="primary-btn" data-action="export">导出数据</button>')}<div class="grid settings-grid"><section class="card setting-card"><div class="card-title"><h2>隐私与数据</h2><span class="data-badge">本地优先</span></div><div class="setting-row"><div><strong>云端同步</strong><small>开启前会单独说明数据用途</small></div><button class="toggle ${state.sync?'on':''}" data-action="toggle" data-key="sync" aria-label="云端同步"></button></div><div class="setting-row"><div><strong>数据地图</strong><small>查看收集字段、用途与保存位置</small></div><button class="text-link" data-action="privacy">查看 →</button></div><div class="setting-row"><div><strong>导出记录</strong><small>CSV / JSON，本地生成</small></div><button class="text-link" data-action="export">导出 →</button></div><div class="setting-row"><div><strong>删除所有数据</strong><small>删除后无法恢复</small></div><button class="ghost-btn danger-btn" data-action="delete">删除</button></div></section><section class="card setting-card"><div class="card-title"><h2>提醒设置</h2><span class="subtle">默认关闭</span></div><div class="setting-row"><div><strong>经期将至提醒</strong><small>使用中性文案，不在锁屏显示敏感内容</small></div><button class="toggle ${state.reminders?'on':''}" data-action="toggle" data-key="reminders" aria-label="经期提醒"></button></div><div class="setting-row"><div><strong>静默时段</strong><small>22:00—08:00</small></div><button class="toggle ${state.quiet?'on':''}" data-action="toggle" data-key="quiet" aria-label="静默时段"></button></div><div class="setting-row"><div><strong>记录提醒</strong><small>经期中每天最多一次</small></div><span class="subtle">未开启</span></div></section><section class="card setting-card"><div class="card-title"><h2>周期偏好</h2></div><div class="setting-row"><div><strong>使用模式</strong><small>经期管理</small></div><button class="text-link">修改 →</button></div><div class="setting-row"><div><strong>通常周期</strong><small>${state.cycleLength} 天</small></div><button class="text-link">修改 →</button></div></section><section class="card setting-card"><div class="card-title"><h2>关于 Cyclea</h2></div><p class="subtle" style="line-height:1.8">Cyclea 提供记录和统计估计，不构成医疗诊断、避孕承诺或受孕保证。出现紧急症状时，请优先联系当地紧急医疗服务。</p></section></div>`}
function render(){renderNav();document.getElementById('main').innerHTML=({home,calendar,trends,knowledge,profile}[state.page]||home)();document.getElementById('main').focus({preventScroll:true});save()}
function showModal(html){const m=document.getElementById('modal');m.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true">${html}</div>`;m.hidden=false}
function closeModal(){document.getElementById('modal').hidden=true}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function onboarding(){showModal(`<div class="onboard-mark">C</div><span class="eyebrow" style="display:block;margin-top:18px">欢迎来到 Cyclea</span><h2>更了解周期，也更安心。</h2><p>不注册也可以使用。只需要最近一次经期信息，就能得到第一个预测区间。</p><div class="form-group"><label>最近一次经期开始日</label><input id="onboardDate" type="date" value="${state.lastStart}" max="${iso(today)}"></div><div class="form-group"><label>通常周期长度（天）</label><input id="onboardCycle" type="number" min="20" max="60" value="${state.cycleLength}"></div><div class="privacy-promise">⌁ 数据默认只保存在这台设备，随时可以导出或删除。</div><div class="modal-actions"><button class="ghost-btn" data-action="onboardSkip">稍后设置</button><button class="primary-btn" data-action="onboardDone">以游客身份开始</button></div>`) }
function logModal(type){const labels={flow:['记录流量',['点滴','少','中','多']],pain:['记录疼痛',['无','轻','中','重']],mood:['记录情绪',['平静','敏感','低落','愉快']]},x=labels[type]||['今日打卡',['流量','疼痛','情绪','睡眠']];showModal(`<span class="eyebrow">${fmt(today,{month:'long',day:'numeric'})}</span><h2>${x[0]}</h2><p>选择最接近今天感受的一项，也可以留空。</p><div class="choice-grid">${x[1].map((n,i)=>`<button class="choice ${i===1?'selected':''}" data-choice="${n}">${n}</button>`).join('')}</div><div class="form-group"><label>私密备注（不会默认进入报告）</label><textarea id="note" placeholder="写下一点想记住的事…"></textarea></div><div class="modal-actions"><button class="ghost-btn" data-action="close">取消</button><button class="primary-btn" data-action="saveLog" data-type="${type}">保存记录</button></div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='navigate'){state.page=b.dataset.page;render()}if(a==='close')closeModal();if(a==='quickLog')logModal('all');if(a==='log')logModal(b.dataset.type);if(a==='saveLog'){const selected=document.querySelector('.choice.selected')?.dataset.choice||'已记录';state.logs[iso(today)]={...(state.logs[iso(today)]||{}),[b.dataset.type]:selected,note:document.getElementById('note')?.value||''};closeModal();render();toast('已安全保存在此设备')}if(a==='period'){state.periodActive=!state.periodActive;if(state.periodActive)state.lastStart=iso(today);render();toast(state.periodActive?'已记录今天开始':'经期已结束并保存')}if(a==='toggle'){state[b.dataset.key]=!state[b.dataset.key];render();toast(state[b.dataset.key]?'已开启':'已关闭')}if(a==='onboardDone'){state.lastStart=document.getElementById('onboardDate').value;state.cycleLength=Number(document.getElementById('onboardCycle').value)||28;state.onboarded=true;closeModal();render();toast('你的第一个预测区间已生成')}if(a==='onboardSkip'){state.onboarded=true;closeModal();render()}if(a==='privacy')showModal(`<span class="eyebrow">隐私状态</span><h2>你的数据，由你掌控</h2><div class="record-list"><div class="record-item"><span>⌁</span><div><strong>周期与症状记录</strong><small>仅保存在当前浏览器</small></div></div><div class="record-item"><span>◌</span><div><strong>云同步</strong><small>${state.sync?'已开启':'未开启'}</small></div></div><div class="record-item"><span>×</span><div><strong>广告与跨站追踪</strong><small>不使用</small></div></div></div><div class="modal-actions"><button class="primary-btn" data-action="close">知道了</button></div>`);if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='cyclea-data.json';link.click();URL.revokeObjectURL(url);toast('数据已在本地生成')}if(a==='delete')showModal(`<span class="eyebrow">不可撤销</span><h2>删除所有本地数据？</h2><p>删除后将无法恢复这些记录。此操作只影响当前设备。</p><div class="modal-actions"><button class="ghost-btn" data-action="close">取消</button><button class="ghost-btn danger-btn" data-action="confirmDelete">确认删除</button></div>`);if(a==='confirmDelete'){localStorage.removeItem('cyclea-state');state={...defaultState,onboarded:true};closeModal();render();toast('本地数据已删除')}if(a==='date')logModal('all')});
document.addEventListener('click',e=>{const c=e.target.closest('.choice');if(c){c.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}});
render();if(!state.onboarded)setTimeout(onboarding,250);
